from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Course',
    'Lesson',
    'UserProgress',
    'Question',
    'UserExamAttempt',
    'Payment',
    'BlogPost',
    'AboutContent',
    'SubscriptionPlan',
    'Testimonial',
    'InterviewQuestion',
    'LearningPath',
    'CourseOnLearningPath',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'progress': 'UserProgress',
        'attempts': 'UserExamAttempt',
        'payments': 'Payment',
    },
    'Course': {
        'lessons': 'Lesson',
        'learningPaths': 'CourseOnLearningPath',
    },
    'Lesson': {
        'course': 'Course',
        'progress': 'UserProgress',
    },
    'UserProgress': {
        'user': 'User',
        'lesson': 'Lesson',
    },
    'Question': {
    },
    'UserExamAttempt': {
        'user': 'User',
    },
    'Payment': {
        'user': 'User',
    },
    'BlogPost': {
    },
    'AboutContent': {
    },
    'SubscriptionPlan': {
    },
    'Testimonial': {
    },
    'InterviewQuestion': {
    },
    'LearningPath': {
        'courses': 'CourseOnLearningPath',
    },
    'CourseOnLearningPath': {
        'learningPath': 'LearningPath',
        'course': 'Course',
    },
}

# fmt: on